### ISSUE TITLE
Recommend to make a same function to ctrl-6 navigation, thanks

### ISSUE THREAD

**Issue by oit63** [tyeen/OpenQuicklyCtrlNP#1]
maybe the ctrl-6 drop menu need a same function as quick open

**Comment by tyeen** [comment]
Good idea! It would be much more convenient to navigate the document items by ctrl+n/p. However, that is beyond this plug-in.
And personally, I'd like to just type the target after popping up ctrl-6 panel, instead of navigating.
PS: my another plug-in "BlockJump" can jump between the same items as in ctrl-6 panel. You may give a try;)
